name: "Weekly Interaction"
on: 
  schedule:
    - cron: "0 15 * 1-4,9-12 0"

jobs:
  interact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - name: Pair or Check In on Buddies
        env: 
          SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
          PAIRINGS_PATH: ${{ secrets.PAIRINGS_PATH }}
          DB_ACCESS_KEY_ID: ${{ secrets.DB_ACCESS_KEY_ID }}
          DB_SECRET_ACCESS_KEY: ${{ secrets.DB_SECRET_ACCESS_KEY }}
          DB_DEFAULT_REGION: ${{ secrets.DB_DEFAULT_REGION }}
        run: npm run weekly
